site_name: AVerMedia Developer Hub
site_url: https://avermedia-hanson.github.io/docs-proto/

theme:
  name: "material"
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tooltips
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    annotation: material/arrow-right-circle

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - admonition
  - pymdownx.blocks.caption
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - Softwares:
    - softwares/index.md
    - Some Streaming SDK:
      - softwares/some-streaming-sdk/index.md
      - Getting Started: softwares/some-streaming-sdk/getting-started.md
      - Examples:
        - softwares/some-streaming-sdk/examples/index.md
        - Use Case 1: softwares/some-streaming-sdk/examples/use-case-1.md
        - Use Case 2: softwares/some-streaming-sdk/examples/use-case-2.md
      - API Reference: softwares/some-streaming-sdk/api/index.md
    - Some Audio SDK:
      - softwares/some-audio-sdk/index.md
    - Some Video SDK:
      - softwares/some-video-sdk/index.html
    - Some AI SDK:
      - softwares/some-ai-sdk/index.md
  - Internal:
    - internal/index.md
    - 文件撰寫規範: internal/guidelines.md
    - Material for MkDocs 教學:
      - internal/tutorial-zhtw/index.md
      - 快速開始: internal/tutorial-zhtw/getting-started.md
      - 如何撰寫 Markdown 文件:
        - internal/tutorial-zhtw/markdown/index.md
        - 基本語法: internal/tutorial-zhtw/markdown/basic.md
        - Material for MkDocs 擴充語法: internal/tutorial-zhtw/markdown/extensions.md
        - HTML 區塊: internal/tutorial-zhtw/markdown/html-blocks.md
      - 設定 MkDocs 專案: internal/tutorial-zhtw/configuration.md
      - 建立不同版本的文件: internal/tutorial-zhtw/versioning.md
