site_name: AVerMedia Developer Hub
site_url: https://avermedia-hanson.github.io/docs-proto/

theme:
  name: "material"
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Softwares:
    - softwares/index.md
    - Some Streaming SDK:
      - softwares/some-streaming-sdk/index.md
      - Getting Started: softwares/some-streaming-sdk/getting-started.md
      - Examples:
        - softwares/some-streaming-sdk/examples/index.md
        - Use Case 1: softwares/some-streaming-sdk/examples/use-case-1.md
        - Use Case 2: softwares/some-streaming-sdk/examples/use-case-2.md
      - API Reference: softwares/some-streaming-sdk/api/index.md
    - Some Audio SDK:
      - softwares/some-audio-sdk/index.md
    - Some Video SDK:
      - softwares/some-video-sdk/index.html
    - Some AI SDK:
      - softwares/some-ai-sdk/index.md
  - Internal:
    - internal/index.md
    - Overview: internal/overview.md
    - Docs Writing Guide: internal/docs-writing-guide.md
    - Maintenance Guide: internal/maintenance-guide.md
